server.port=8082

spring.application.name=trip-service
spring.datasource.url=jdbc:postgresql://localhost:5433/Trip-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username= postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

grpc.server.port=9092
grpc.client.user-service.address=static://localhost:9091
grpc.client.user-service.negotiation-type=plaintext

app.jwt.secret=bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXk=
